/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalhom1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ian
 */
public class SelecaoItens extends javax.swing.JFrame {

    /**
     * Creates new form SelecaoItens
     */
    CampeaoStats champ;
    ItensStats[] itensSelecionados = new ItensStats[6];

    ItensMetodos itemMet = new ItensMetodos();
    
    public SelecaoItens(CampeaoStats campeao) {
        champ = campeao;
        
        for(int i = 0; i < itensSelecionados.length; i++){
            itensSelecionados[i] = new ItensStats();
        }
        initComponents();
        DisplayTable();
    }  
    
    public SelecaoItens(){
        initComponents();
        DisplayTable();
    }
    
    private void DisplayTable(){

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://179.220.42.166:3306/leagueoflegends?zeroDateTimeBehavior=convertToNull", "viewer", "");
            String query = "SELECT Name,Life,Armour,MagicResist,ATKDMG,VelATK,CritChance,MagicDMG,Mana,MovSpeed,PercMovSpeed,LifeSteal FROM itens ORDER BY Name";
            PreparedStatement pstmt = (PreparedStatement) conn.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldItem1 = new javax.swing.JTextField();
        jTextFieldItem2 = new javax.swing.JTextField();
        jTextFieldItem3 = new javax.swing.JTextField();
        jTextFieldItem4 = new javax.swing.JTextField();
        jTextFieldItem5 = new javax.swing.JTextField();
        jTextFieldItem6 = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel2.setText("Selecione Seus Itens");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Life", "Armour", "Magic Resist", "Attack Damage", "Attack Speed", "Crit Chance", "Dano Mágico", "Mov Speed", "% ATK Speed", "Life Steal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonVoltar.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jCheckBox1.setText("Item 1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jCheckBox2.setText("Item 2");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jCheckBox3.setText("Item 3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jCheckBox4.setText("Item 4");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jCheckBox5.setText("Item 5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jCheckBox6.setText("Item 6");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButtonSalvar.setText("Salvar Item");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTextFieldItem1.setText("");
        jTextFieldItem1.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N

        jTextFieldItem2.setText("");
        jTextFieldItem2.setEditable(false);
        jTextFieldItem2.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N

        jTextFieldItem3.setText("");
        jTextFieldItem3.setEditable(false);
        jTextFieldItem3.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N

        jTextFieldItem4.setText("");
        jTextFieldItem4.setEditable(false);
        jTextFieldItem4.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N

        jTextFieldItem5.setText("");
        jTextFieldItem5.setEditable(false);
        jTextFieldItem5.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N

        jTextFieldItem6.setText("");
        jTextFieldItem6.setEditable(false);
        jTextFieldItem6.setFont(new java.awt.Font("Maiandra GD", 0, 11)); // NOI18N

        jButtonReset.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButtonReset.setText("Resetar Itens");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addComponent(jButtonSalvar)
                .addGap(145, 145, 145)
                .addComponent(jButtonReset)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jTextFieldItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jTextFieldItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBox2)
                                            .addComponent(jCheckBox5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBox3)
                                            .addComponent(jCheckBox6)))
                                    .addComponent(jTextFieldItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
        JFrame inicio = new SelecaoCampeao();
        inicio.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = 0;
        int row = jTable1.getSelectedRow();
        String value = jTable1.getModel().getValueAt(row, column).toString();
        
        if(jCheckBox1.isEnabled()){
            jTextFieldItem1.setText(value);
        } else if(jCheckBox2.isEnabled()){
            jTextFieldItem2.setText(value);
        } else if(jCheckBox3.isEnabled()){
            jTextFieldItem3.setText(value);
        } else if(jCheckBox4.isEnabled()){
            jTextFieldItem4.setText(value);
        } else if(jCheckBox5.isEnabled()){
            jTextFieldItem5.setText(value);
        } else if(jCheckBox6.isEnabled()){
            jTextFieldItem6.setText(value);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jTextFieldItem1.setEditable(false);
        jCheckBox1.setEnabled(false);
        
        if(jTextFieldItem1.getText() != null){
            itensSelecionados[0] = itemMet.pesquisaItem(jTextFieldItem1.getText());
        } else if("".equals(jTextFieldItem1.getText())){
            itensSelecionados[0] = new ItensStats();
        }
        jTextFieldItem2.setEditable(true);
        jCheckBox2.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        jTextFieldItem2.setEditable(false);
        jCheckBox2.setEnabled(false);
        
        if(jTextFieldItem2.getText() != null){
            itensSelecionados[1] = itemMet.pesquisaItem(jTextFieldItem2.getText());
        } else if("".equals(jTextFieldItem2.getText())){
            itensSelecionados[1] = new ItensStats();
        }
        
        jTextFieldItem3.setEditable(true);
        jCheckBox3.setEnabled(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        jTextFieldItem3.setEditable(false);
        jCheckBox3.setEnabled(false);
        
        if(!"".equals(jTextFieldItem3.getText())){
        itensSelecionados[2] = itemMet.pesquisaItem(jTextFieldItem3.getText());
        } else if("".equals(jTextFieldItem2.getText())){
            itensSelecionados[2] = new ItensStats();
        }
        
        jTextFieldItem4.setEditable(true);
        jCheckBox4.setEnabled(true);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        jTextFieldItem4.setEditable(false);
        jCheckBox4.setEnabled(false);
        
        if(!"".equals(jTextFieldItem4.getText())){
            itensSelecionados[3] = itemMet.pesquisaItem(jTextFieldItem4.getText());
        } else if("".equals(jTextFieldItem3.getText())){
            itensSelecionados[3] = new ItensStats();
        }
        
        jTextFieldItem5.setEditable(true);
        jCheckBox5.setEnabled(true);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        jTextFieldItem5.setEditable(false);
        jCheckBox5.setEnabled(false);
        
        if(!"".equals(jTextFieldItem5.getText())){
            itensSelecionados[4] = itemMet.pesquisaItem(jTextFieldItem5.getText());
        } else if("".equals(jTextFieldItem4.getText())){
            itensSelecionados[4] = new ItensStats();
        }
        
        jTextFieldItem6.setEditable(true);
        jCheckBox6.setEnabled(true);
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        jTextFieldItem6.setEditable(false);
        jCheckBox6.setEnabled(false);
        
        if(!"".equals(jTextFieldItem6.getText())){
            itensSelecionados[5] = itemMet.pesquisaItem(jTextFieldItem6.getText());
        } else if("".equals(jTextFieldItem5.getText())){
            itensSelecionados[5] = new ItensStats();
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jCheckBox1.setSelected(false);
        jCheckBox1.setEnabled(true);
        jTextFieldItem1.setEditable(true); jTextFieldItem1.setText(null);
        
        jCheckBox2.setSelected(false);
        jCheckBox2.setEnabled(false);
        jTextFieldItem2.setEditable(false); jTextFieldItem2.setText(null);
        
        jCheckBox3.setSelected(false);
        jCheckBox3.setEnabled(false);
        jTextFieldItem3.setEditable(false); jTextFieldItem3.setText(null);
        
        jCheckBox4.setSelected(false);
        jCheckBox4.setEnabled(false);
        jTextFieldItem4.setEditable(false); jTextFieldItem4.setText(null);
        
        jCheckBox5.setSelected(false);
        jCheckBox5.setEnabled(false);
        jTextFieldItem5.setEditable(false); jTextFieldItem5.setText(null);
        
        jCheckBox6.setSelected(false);
        jCheckBox6.setEnabled(false);
        jTextFieldItem6.setEditable(false); jTextFieldItem6.setText(null);
        
        itensSelecionados = new ItensStats[6];
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        System.out.println(champ.getNome());
        JFrame janela = new TelaFinal(itensSelecionados, champ);
        this.dispose();
        janela.setVisible(true);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldItem1;
    private javax.swing.JTextField jTextFieldItem2;
    private javax.swing.JTextField jTextFieldItem3;
    private javax.swing.JTextField jTextFieldItem4;
    private javax.swing.JTextField jTextFieldItem5;
    private javax.swing.JTextField jTextFieldItem6;
    // End of variables declaration//GEN-END:variables
}
