/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalhom1;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author ian
 */
public class TelaFinal extends javax.swing.JFrame {

     ItensStats[] itens;
     CampeaoStats champ;
     Image image;
    /**
     * Creates new form TelaFinal
     * @param item
     * @param champion
     */
    public TelaFinal(ItensStats[] item, CampeaoStats champion) {
        itens = item;
        champ = champion;
        
        
        initComponents();
        showMessageDialog(null, "Digite um nível e aperte para atualizar.");
        jLabel2.setIcon(pegaImagem(champ.getNome()));
        
    }
    
    public TelaFinal(){
        initComponents();
    }
    
        private ImageIcon pegaImagem(String nome) {
        ImageIcon teste = null;
        try{
            URL url = new URL(String.format("https://ddragon.leagueoflegends.com/cdn/10.19.1/img/champion/%s.png",nome));
            image = ImageIO.read(url);
            teste=new ImageIcon(url);
            
        }
        catch(IOException e){
            
        }
        return teste;
    }
    
    private void setLabels(ItensStats[] itens, CampeaoStats champ, int lvl){
        
        jLabelStatsNome.setText(champ.getNome());
        
        Double val = champ.getHp();
        val = val + (champ.getHpperlevel() * lvl);
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getVida();
        }
        jLabelStatsVida.setText(Double.toString(val));
        
        val = champ.getMp();
        val += champ.getMpperlevel() * lvl;
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getMana();
        }
        
        jLabelStatsMana.setText(Double.toString(val));
        
        val = champ.getMovespeed();
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getVelocidadeDeMovimento();
        }
        jLabelStatsVelocidadeDeMovimento.setText(Double.toString(val));
        
        val = champ.getArmor();
        val += champ.getArmorperlevel() * lvl;
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getArmadura();
        }
        jLabelStatsArmadura.setText(String.format("%.2f",val));
        
        val = champ.getSpellblock();
        val += champ.getSpellblockperlevel()* lvl;
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getResistenciaMagica();
        }
        jLabelStatsResistenciaMagica.setText(String.format("%.2f",val));
        
        jLabelStatsAlcance.setText(Double.toString(champ.getAttackrange()));
        
        val = champ.getHpregen();
        val += (champ.getHpregenperlevel() / 100) * lvl;
        jLabelStatsRegenVida.setText(String.format("%.2f",val));
        
        
        val = champ.getMpregen();
        val += (champ.getMpperlevel() / 100) * lvl;
        jLabelStatsRegenMana.setText(String.format("%.2f",val));
        
        val = champ.getCrit();
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getChanceDeAcertoCritico();
        }
        jLabelStatsChanceCritico.setText(Double.toString(val));
        
        val = champ.getAttackdamage();
        val += champ.getAttackdamageperlevel() * lvl;
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getDanoDeAtaque();
        }
        jLabelStatsDanoDeAtaque.setText(Double.toString(val));
        
        
        val = champ.getAttackspeed();
        val += (champ.getAttackspeedperlevel() / 100)* lvl;
        for(int i = 0; i < itens.length; i++){
            val += itens[i].getVelocidadeDeAtaque();
        }
        jLabelStatsVelocidadeDeAtaque.setText(String.format("%.2f",val));
        
        jLabelNomeItem1.setText(itens[0].getNome());
        jLabelNomeItem2.setText(itens[1].getNome());
        jLabelNomeItem3.setText(itens[2].getNome());
        jLabelNomeItem4.setText(itens[3].getNome());
        jLabelNomeItem5.setText(itens[4].getNome());
        jLabelNomeItem6.setText(itens[5].getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeChamp = new javax.swing.JLabel();
        jLabelTituloStats = new javax.swing.JLabel();
        jLabelTituloItens = new javax.swing.JLabel();
        jLabelVidaChamp = new javax.swing.JLabel();
        jLabelMana = new javax.swing.JLabel();
        jLabelVelocidadeDeMovimento = new javax.swing.JLabel();
        jLabelArmadura = new javax.swing.JLabel();
        jLabelResistenciaMagica = new javax.swing.JLabel();
        jLabelAlcance = new javax.swing.JLabel();
        jLabelRegenVida = new javax.swing.JLabel();
        jLabelChanceCritico = new javax.swing.JLabel();
        jLabelRegenMana = new javax.swing.JLabel();
        jLabelDanoDeAtaque = new javax.swing.JLabel();
        jLabelVelocidadeDeAtaque = new javax.swing.JLabel();
        jLabelStatsNome = new javax.swing.JLabel();
        jLabelStatsVida = new javax.swing.JLabel();
        jLabelStatsMana = new javax.swing.JLabel();
        jLabelStatsVelocidadeDeMovimento = new javax.swing.JLabel();
        jLabelStatsArmadura = new javax.swing.JLabel();
        jLabelStatsResistenciaMagica = new javax.swing.JLabel();
        jLabelStatsAlcance = new javax.swing.JLabel();
        jLabelStatsRegenVida = new javax.swing.JLabel();
        jLabelStatsRegenMana = new javax.swing.JLabel();
        jLabelStatsChanceCritico = new javax.swing.JLabel();
        jLabelStatsDanoDeAtaque = new javax.swing.JLabel();
        jLabelStatsVelocidadeDeAtaque = new javax.swing.JLabel();
        jLabelItem1 = new javax.swing.JLabel();
        jLabelItem2 = new javax.swing.JLabel();
        jLabelItem4 = new javax.swing.JLabel();
        jLabelItem3 = new javax.swing.JLabel();
        jLabelItem5 = new javax.swing.JLabel();
        jLabelItem6 = new javax.swing.JLabel();
        jLabelNomeItem2 = new javax.swing.JLabel();
        jLabelNomeItem1 = new javax.swing.JLabel();
        jLabelNomeItem3 = new javax.swing.JLabel();
        jLabelNomeItem4 = new javax.swing.JLabel();
        jLabelNomeItem5 = new javax.swing.JLabel();
        jLabelNomeItem6 = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();
        jTextFieldLevel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNomeChamp.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelNomeChamp.setText("Nome:");

        jLabelTituloStats.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabelTituloStats.setText("Status Finais");

        jLabelTituloItens.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabelTituloItens.setText("Itens Selecionados");

        jLabelVidaChamp.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelVidaChamp.setText("Vida:");

        jLabelMana.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelMana.setText("Mana:");

        jLabelVelocidadeDeMovimento.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelVelocidadeDeMovimento.setText("Velocidade de Movimento:");

        jLabelArmadura.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelArmadura.setText("Armadura:");

        jLabelResistenciaMagica.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelResistenciaMagica.setText("Resistencia Mágica:");

        jLabelAlcance.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelAlcance.setText("Alcance:");

        jLabelRegenVida.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelRegenVida.setText("Regeneração de Vida:");

        jLabelChanceCritico.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelChanceCritico.setText("Chance de Crítico:");

        jLabelRegenMana.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelRegenMana.setText("Regeneração de Mana:");

        jLabelDanoDeAtaque.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelDanoDeAtaque.setText("Dano de Ataque:");

        jLabelVelocidadeDeAtaque.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelVelocidadeDeAtaque.setText("Velocidade de Ataque:");

        jLabelStatsNome.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsNome.setText("         ");

        jLabelStatsVida.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsVida.setText("         ");

        jLabelStatsMana.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsMana.setText("         ");

        jLabelStatsVelocidadeDeMovimento.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsVelocidadeDeMovimento.setText("         ");

        jLabelStatsArmadura.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsArmadura.setText("         ");

        jLabelStatsResistenciaMagica.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsResistenciaMagica.setText("          ");

        jLabelStatsAlcance.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsAlcance.setText("          ");

        jLabelStatsRegenVida.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsRegenVida.setText("          ");

        jLabelStatsRegenMana.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsRegenMana.setText("          ");

        jLabelStatsChanceCritico.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsChanceCritico.setText("          ");

        jLabelStatsDanoDeAtaque.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsDanoDeAtaque.setText("          ");

        jLabelStatsVelocidadeDeAtaque.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jLabelStatsVelocidadeDeAtaque.setText("          ");

        jLabelItem1.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelItem1.setText("Item 1:");

        jLabelItem2.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelItem2.setText("Item 2:");

        jLabelItem4.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelItem4.setText("Item 4:");

        jLabelItem3.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelItem3.setText("Item 3:");

        jLabelItem5.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelItem5.setText("Item 5:");

        jLabelItem6.setFont(new java.awt.Font("Maiandra GD", 1, 13)); // NOI18N
        jLabelItem6.setText("Item 6:");

        jLabelNomeItem2.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabelNomeItem2.setText("                     ");

        jLabelNomeItem1.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabelNomeItem1.setText("                     ");

        jLabelNomeItem3.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabelNomeItem3.setText("                     ");

        jLabelNomeItem4.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabelNomeItem4.setText("                     ");

        jLabelNomeItem5.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabelNomeItem5.setText("                     ");

        jLabelNomeItem6.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabelNomeItem6.setText("                     ");

        jButtonAtualizar.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jButtonAtualizar.setText("ATUALIZAR");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jTextFieldLevel.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jTextFieldLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLevelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel1.setText("Digite o nível que seu campeão estaria (Entre 1 e 18)");

        jLabel2.setText("          ");

        jButton1.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelVelocidadeDeAtaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelStatsVelocidadeDeAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(487, 487, 487))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelVelocidadeDeMovimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelStatsVelocidadeDeMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelDanoDeAtaque)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelStatsDanoDeAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelChanceCritico)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelStatsChanceCritico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelRegenMana, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelStatsRegenMana, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelRegenVida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelStatsRegenVida, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTituloStats, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabelMana, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabelVidaChamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabelNomeChamp, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelStatsMana, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelStatsVida, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelStatsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelAlcance)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelStatsAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelResistenciaMagica)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabelStatsResistenciaMagica, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelArmadura)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelStatsArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloItens, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelItem6)
                                .addComponent(jLabelItem5)
                                .addComponent(jLabelItem4)
                                .addComponent(jLabelItem3)
                                .addComponent(jLabelItem2))
                            .addComponent(jLabelItem1))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNomeItem3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNomeItem4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNomeItem5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNomeItem6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNomeItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(524, 524, 524)
                                .addComponent(jTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloStats, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTituloItens, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomeChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStatsNome)
                            .addComponent(jLabelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVidaChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStatsVida)
                            .addComponent(jLabelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMana, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStatsMana)
                            .addComponent(jLabelItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVelocidadeDeMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsVelocidadeDeMovimento)
                    .addComponent(jLabelItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsArmadura)
                    .addComponent(jLabelItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResistenciaMagica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsResistenciaMagica)
                    .addComponent(jLabelItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsAlcance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegenVida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsRegenVida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegenMana, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsRegenMana))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChanceCritico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsChanceCritico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDanoDeAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsDanoDeAtaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVelocidadeDeAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatsVelocidadeDeAtaque))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean isInteger(String s){
        try{
            Integer.parseInt(jTextFieldLevel.getText());
            return true;
        } catch(NumberFormatException e){
            return false;
        }
    }
    
    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        int lvl;

        if(!isInteger(jTextFieldLevel.getText())){
            showMessageDialog(null, "Valor digitado é diferente de um numero inteiro !!!");
        } else{
            lvl = Integer.parseInt(jTextFieldLevel.getText());
            
            if(lvl < 1 || lvl > 18){
                showMessageDialog(null, "Digite um valor válido para o nível !!!");
            }else{
                setLabels(itens, champ, lvl-1);
            }
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTextFieldLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLevelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame janela = new Inicio();
        this.dispose();
        janela.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlcance;
    private javax.swing.JLabel jLabelArmadura;
    private javax.swing.JLabel jLabelChanceCritico;
    private javax.swing.JLabel jLabelDanoDeAtaque;
    private javax.swing.JLabel jLabelItem1;
    private javax.swing.JLabel jLabelItem2;
    private javax.swing.JLabel jLabelItem3;
    private javax.swing.JLabel jLabelItem4;
    private javax.swing.JLabel jLabelItem5;
    private javax.swing.JLabel jLabelItem6;
    private javax.swing.JLabel jLabelMana;
    private javax.swing.JLabel jLabelNomeChamp;
    private javax.swing.JLabel jLabelNomeItem1;
    private javax.swing.JLabel jLabelNomeItem2;
    private javax.swing.JLabel jLabelNomeItem3;
    private javax.swing.JLabel jLabelNomeItem4;
    private javax.swing.JLabel jLabelNomeItem5;
    private javax.swing.JLabel jLabelNomeItem6;
    private javax.swing.JLabel jLabelRegenMana;
    private javax.swing.JLabel jLabelRegenVida;
    private javax.swing.JLabel jLabelResistenciaMagica;
    private javax.swing.JLabel jLabelStatsAlcance;
    private javax.swing.JLabel jLabelStatsArmadura;
    private javax.swing.JLabel jLabelStatsChanceCritico;
    private javax.swing.JLabel jLabelStatsDanoDeAtaque;
    private javax.swing.JLabel jLabelStatsMana;
    private javax.swing.JLabel jLabelStatsNome;
    private javax.swing.JLabel jLabelStatsRegenMana;
    private javax.swing.JLabel jLabelStatsRegenVida;
    private javax.swing.JLabel jLabelStatsResistenciaMagica;
    private javax.swing.JLabel jLabelStatsVelocidadeDeAtaque;
    private javax.swing.JLabel jLabelStatsVelocidadeDeMovimento;
    private javax.swing.JLabel jLabelStatsVida;
    private javax.swing.JLabel jLabelTituloItens;
    private javax.swing.JLabel jLabelTituloStats;
    private javax.swing.JLabel jLabelVelocidadeDeAtaque;
    private javax.swing.JLabel jLabelVelocidadeDeMovimento;
    private javax.swing.JLabel jLabelVidaChamp;
    private javax.swing.JTextField jTextFieldLevel;
    // End of variables declaration//GEN-END:variables
}
